/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EmailsRouteImport } from './routes/emails'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ShippingReturnsRouteImport } from './routes/shipping-returns'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SizeGuideRouteImport } from './routes/size-guide'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TrackOrderRouteImport } from './routes/track-order'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAbandonedRouteImport } from './routes/admin/abandoned'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as AdminBackInStockRouteImport } from './routes/admin/back-in-stock'
import { Route as AdminCustomersRouteImport } from './routes/admin/customers'
import { Route as AdminDiscountsRouteImport } from './routes/admin/discounts'
import { Route as AdminDraftsRouteImport } from './routes/admin/drafts'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminStaffRouteImport } from './routes/admin/staff'
import { Route as AdminSubscribersRouteImport } from './routes/admin/subscribers'
import { Route as AdminSystemRouteImport } from './routes/admin/system'
import { Route as AdminLoginRouteImport } from './routes/admin_.login'
import { Route as OrderIdRouteImport } from './routes/order.$id'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as AdminContentAnnouncementsRouteImport } from './routes/admin/content.announcements'
import { Route as AdminContentBrandRouteImport } from './routes/admin/content.brand'
import { Route as AdminContentFooterRouteImport } from './routes/admin/content.footer'
import { Route as AdminContentHeaderRouteImport } from './routes/admin/content.header'
import { Route as AdminContentHeroRouteImport } from './routes/admin/content.hero'
import { Route as AdminContentHomeRouteImport } from './routes/admin/content.home'
import { Route as AdminContentNewsletterRouteImport } from './routes/admin/content.newsletter'
import { Route as AdminContentPagesRouteImport } from './routes/admin/content.pages'
import { Route as AdminContentPromoRouteImport } from './routes/admin/content.promo'
import { Route as AdminContentTestimonialsRouteImport } from './routes/admin/content.testimonials'
import { Route as AdminContentThemeRouteImport } from './routes/admin/content.theme'
import { Route as AdminCustomersIdRouteImport } from './routes/admin/customers.$id'
import { Route as AdminOrdersIdRouteImport } from './routes/admin/orders.$id'
import { Route as AdminProductsIdRouteImport } from './routes/admin/products.$id'
import { Route as AdminSettingsCountriesRouteImport } from './routes/admin/settings.countries'
import { Route as AdminSettingsCouriersRouteImport } from './routes/admin/settings.couriers'
import { Route as AdminSettingsCurrencyRouteImport } from './routes/admin/settings.currency'
import { Route as AdminSettingsOrdersRouteImport } from './routes/admin/settings.orders'
import { Route as AdminSettingsPaymentsRouteImport } from './routes/admin/settings.payments'
import { Route as AdminSettingsShippingRouteImport } from './routes/admin/settings.shipping'
import { Route as AdminSettingsStoreRouteImport } from './routes/admin/settings.store'
import { Route as AdminSettingsTaxRouteImport } from './routes/admin/settings.tax'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailsRoute = EmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingReturnsRoute = ShippingReturnsRouteImport.update({
  id: '/shipping-returns',
  path: '/shipping-returns',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SizeGuideRoute = SizeGuideRouteImport.update({
  id: '/size-guide',
  path: '/size-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackOrderRoute = TrackOrderRouteImport.update({
  id: '/track-order',
  path: '/track-order',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAbandonedRoute = AdminAbandonedRouteImport.update({
  id: '/abandoned',
  path: '/abandoned',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBackInStockRoute = AdminBackInStockRouteImport.update({
  id: '/back-in-stock',
  path: '/back-in-stock',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDiscountsRoute = AdminDiscountsRouteImport.update({
  id: '/discounts',
  path: '/discounts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDraftsRoute = AdminDraftsRouteImport.update({
  id: '/drafts',
  path: '/drafts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscribersRoute = AdminSubscribersRouteImport.update({
  id: '/subscribers',
  path: '/subscribers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSystemRoute = AdminSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin_/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderIdRoute = OrderIdRouteImport.update({
  id: '/order/$id',
  path: '/order/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContentAnnouncementsRoute =
  AdminContentAnnouncementsRouteImport.update({
    id: '/content/announcements',
    path: '/content/announcements',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminContentBrandRoute = AdminContentBrandRouteImport.update({
  id: '/content/brand',
  path: '/content/brand',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentFooterRoute = AdminContentFooterRouteImport.update({
  id: '/content/footer',
  path: '/content/footer',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentHeaderRoute = AdminContentHeaderRouteImport.update({
  id: '/content/header',
  path: '/content/header',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentHeroRoute = AdminContentHeroRouteImport.update({
  id: '/content/hero',
  path: '/content/hero',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentHomeRoute = AdminContentHomeRouteImport.update({
  id: '/content/home',
  path: '/content/home',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentNewsletterRoute = AdminContentNewsletterRouteImport.update({
  id: '/content/newsletter',
  path: '/content/newsletter',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentPagesRoute = AdminContentPagesRouteImport.update({
  id: '/content/pages',
  path: '/content/pages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentPromoRoute = AdminContentPromoRouteImport.update({
  id: '/content/promo',
  path: '/content/promo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentTestimonialsRoute =
  AdminContentTestimonialsRouteImport.update({
    id: '/content/testimonials',
    path: '/content/testimonials',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminContentThemeRoute = AdminContentThemeRouteImport.update({
  id: '/content/theme',
  path: '/content/theme',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersIdRoute = AdminCustomersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminCustomersRoute,
} as any)
const AdminOrdersIdRoute = AdminOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminOrdersRoute,
} as any)
const AdminProductsIdRoute = AdminProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminProductsRoute,
} as any)
const AdminSettingsCountriesRoute = AdminSettingsCountriesRouteImport.update({
  id: '/settings/countries',
  path: '/settings/countries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsCouriersRoute = AdminSettingsCouriersRouteImport.update({
  id: '/settings/couriers',
  path: '/settings/couriers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsCurrencyRoute = AdminSettingsCurrencyRouteImport.update({
  id: '/settings/currency',
  path: '/settings/currency',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsOrdersRoute = AdminSettingsOrdersRouteImport.update({
  id: '/settings/orders',
  path: '/settings/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsPaymentsRoute = AdminSettingsPaymentsRouteImport.update({
  id: '/settings/payments',
  path: '/settings/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsShippingRoute = AdminSettingsShippingRouteImport.update({
  id: '/settings/shipping',
  path: '/settings/shipping',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsStoreRoute = AdminSettingsStoreRouteImport.update({
  id: '/settings/store',
  path: '/settings/store',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsTaxRoute = AdminSettingsTaxRouteImport.update({
  id: '/settings/tax',
  path: '/settings/tax',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/emails': typeof EmailsRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shipping-returns': typeof ShippingReturnsRoute
  '/shop': typeof ShopRoute
  '/size-guide': typeof SizeGuideRoute
  '/terms': typeof TermsRoute
  '/track-order': typeof TrackOrderRoute
  '/verify': typeof VerifyRoute
  '/wishlist': typeof WishlistRoute
  '/admin/abandoned': typeof AdminAbandonedRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/back-in-stock': typeof AdminBackInStockRoute
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/discounts': typeof AdminDiscountsRoute
  '/admin/drafts': typeof AdminDraftsRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/staff': typeof AdminStaffRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/login': typeof AdminLoginRoute
  '/order/$id': typeof OrderIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/content/announcements': typeof AdminContentAnnouncementsRoute
  '/admin/content/brand': typeof AdminContentBrandRoute
  '/admin/content/footer': typeof AdminContentFooterRoute
  '/admin/content/header': typeof AdminContentHeaderRoute
  '/admin/content/hero': typeof AdminContentHeroRoute
  '/admin/content/home': typeof AdminContentHomeRoute
  '/admin/content/newsletter': typeof AdminContentNewsletterRoute
  '/admin/content/pages': typeof AdminContentPagesRoute
  '/admin/content/promo': typeof AdminContentPromoRoute
  '/admin/content/testimonials': typeof AdminContentTestimonialsRoute
  '/admin/content/theme': typeof AdminContentThemeRoute
  '/admin/customers/$id': typeof AdminCustomersIdRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/admin/settings/countries': typeof AdminSettingsCountriesRoute
  '/admin/settings/couriers': typeof AdminSettingsCouriersRoute
  '/admin/settings/currency': typeof AdminSettingsCurrencyRoute
  '/admin/settings/orders': typeof AdminSettingsOrdersRoute
  '/admin/settings/payments': typeof AdminSettingsPaymentsRoute
  '/admin/settings/shipping': typeof AdminSettingsShippingRoute
  '/admin/settings/store': typeof AdminSettingsStoreRoute
  '/admin/settings/tax': typeof AdminSettingsTaxRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/emails': typeof EmailsRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shipping-returns': typeof ShippingReturnsRoute
  '/shop': typeof ShopRoute
  '/size-guide': typeof SizeGuideRoute
  '/terms': typeof TermsRoute
  '/track-order': typeof TrackOrderRoute
  '/verify': typeof VerifyRoute
  '/wishlist': typeof WishlistRoute
  '/admin/abandoned': typeof AdminAbandonedRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/back-in-stock': typeof AdminBackInStockRoute
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/discounts': typeof AdminDiscountsRoute
  '/admin/drafts': typeof AdminDraftsRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/staff': typeof AdminStaffRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/login': typeof AdminLoginRoute
  '/order/$id': typeof OrderIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/content/announcements': typeof AdminContentAnnouncementsRoute
  '/admin/content/brand': typeof AdminContentBrandRoute
  '/admin/content/footer': typeof AdminContentFooterRoute
  '/admin/content/header': typeof AdminContentHeaderRoute
  '/admin/content/hero': typeof AdminContentHeroRoute
  '/admin/content/home': typeof AdminContentHomeRoute
  '/admin/content/newsletter': typeof AdminContentNewsletterRoute
  '/admin/content/pages': typeof AdminContentPagesRoute
  '/admin/content/promo': typeof AdminContentPromoRoute
  '/admin/content/testimonials': typeof AdminContentTestimonialsRoute
  '/admin/content/theme': typeof AdminContentThemeRoute
  '/admin/customers/$id': typeof AdminCustomersIdRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/admin/settings/countries': typeof AdminSettingsCountriesRoute
  '/admin/settings/couriers': typeof AdminSettingsCouriersRoute
  '/admin/settings/currency': typeof AdminSettingsCurrencyRoute
  '/admin/settings/orders': typeof AdminSettingsOrdersRoute
  '/admin/settings/payments': typeof AdminSettingsPaymentsRoute
  '/admin/settings/shipping': typeof AdminSettingsShippingRoute
  '/admin/settings/store': typeof AdminSettingsStoreRoute
  '/admin/settings/tax': typeof AdminSettingsTaxRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/emails': typeof EmailsRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shipping-returns': typeof ShippingReturnsRoute
  '/shop': typeof ShopRoute
  '/size-guide': typeof SizeGuideRoute
  '/terms': typeof TermsRoute
  '/track-order': typeof TrackOrderRoute
  '/verify': typeof VerifyRoute
  '/wishlist': typeof WishlistRoute
  '/admin/abandoned': typeof AdminAbandonedRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/back-in-stock': typeof AdminBackInStockRoute
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/discounts': typeof AdminDiscountsRoute
  '/admin/drafts': typeof AdminDraftsRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/staff': typeof AdminStaffRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin_/login': typeof AdminLoginRoute
  '/order/$id': typeof OrderIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/content/announcements': typeof AdminContentAnnouncementsRoute
  '/admin/content/brand': typeof AdminContentBrandRoute
  '/admin/content/footer': typeof AdminContentFooterRoute
  '/admin/content/header': typeof AdminContentHeaderRoute
  '/admin/content/hero': typeof AdminContentHeroRoute
  '/admin/content/home': typeof AdminContentHomeRoute
  '/admin/content/newsletter': typeof AdminContentNewsletterRoute
  '/admin/content/pages': typeof AdminContentPagesRoute
  '/admin/content/promo': typeof AdminContentPromoRoute
  '/admin/content/testimonials': typeof AdminContentTestimonialsRoute
  '/admin/content/theme': typeof AdminContentThemeRoute
  '/admin/customers/$id': typeof AdminCustomersIdRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/admin/settings/countries': typeof AdminSettingsCountriesRoute
  '/admin/settings/couriers': typeof AdminSettingsCouriersRoute
  '/admin/settings/currency': typeof AdminSettingsCurrencyRoute
  '/admin/settings/orders': typeof AdminSettingsOrdersRoute
  '/admin/settings/payments': typeof AdminSettingsPaymentsRoute
  '/admin/settings/shipping': typeof AdminSettingsShippingRoute
  '/admin/settings/store': typeof AdminSettingsStoreRoute
  '/admin/settings/tax': typeof AdminSettingsTaxRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/emails'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/orders'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/shipping-returns'
    | '/shop'
    | '/size-guide'
    | '/terms'
    | '/track-order'
    | '/verify'
    | '/wishlist'
    | '/admin/abandoned'
    | '/admin/audit'
    | '/admin/back-in-stock'
    | '/admin/customers'
    | '/admin/discounts'
    | '/admin/drafts'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/staff'
    | '/admin/subscribers'
    | '/admin/system'
    | '/admin/login'
    | '/order/$id'
    | '/product/$slug'
    | '/admin/'
    | '/admin/content/announcements'
    | '/admin/content/brand'
    | '/admin/content/footer'
    | '/admin/content/header'
    | '/admin/content/hero'
    | '/admin/content/home'
    | '/admin/content/newsletter'
    | '/admin/content/pages'
    | '/admin/content/promo'
    | '/admin/content/testimonials'
    | '/admin/content/theme'
    | '/admin/customers/$id'
    | '/admin/orders/$id'
    | '/admin/products/$id'
    | '/admin/settings/countries'
    | '/admin/settings/couriers'
    | '/admin/settings/currency'
    | '/admin/settings/orders'
    | '/admin/settings/payments'
    | '/admin/settings/shipping'
    | '/admin/settings/store'
    | '/admin/settings/tax'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/emails'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/orders'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/shipping-returns'
    | '/shop'
    | '/size-guide'
    | '/terms'
    | '/track-order'
    | '/verify'
    | '/wishlist'
    | '/admin/abandoned'
    | '/admin/audit'
    | '/admin/back-in-stock'
    | '/admin/customers'
    | '/admin/discounts'
    | '/admin/drafts'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/staff'
    | '/admin/subscribers'
    | '/admin/system'
    | '/admin/login'
    | '/order/$id'
    | '/product/$slug'
    | '/admin'
    | '/admin/content/announcements'
    | '/admin/content/brand'
    | '/admin/content/footer'
    | '/admin/content/header'
    | '/admin/content/hero'
    | '/admin/content/home'
    | '/admin/content/newsletter'
    | '/admin/content/pages'
    | '/admin/content/promo'
    | '/admin/content/testimonials'
    | '/admin/content/theme'
    | '/admin/customers/$id'
    | '/admin/orders/$id'
    | '/admin/products/$id'
    | '/admin/settings/countries'
    | '/admin/settings/couriers'
    | '/admin/settings/currency'
    | '/admin/settings/orders'
    | '/admin/settings/payments'
    | '/admin/settings/shipping'
    | '/admin/settings/store'
    | '/admin/settings/tax'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/emails'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/orders'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/shipping-returns'
    | '/shop'
    | '/size-guide'
    | '/terms'
    | '/track-order'
    | '/verify'
    | '/wishlist'
    | '/admin/abandoned'
    | '/admin/audit'
    | '/admin/back-in-stock'
    | '/admin/customers'
    | '/admin/discounts'
    | '/admin/drafts'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/staff'
    | '/admin/subscribers'
    | '/admin/system'
    | '/admin_/login'
    | '/order/$id'
    | '/product/$slug'
    | '/admin/'
    | '/admin/content/announcements'
    | '/admin/content/brand'
    | '/admin/content/footer'
    | '/admin/content/header'
    | '/admin/content/hero'
    | '/admin/content/home'
    | '/admin/content/newsletter'
    | '/admin/content/pages'
    | '/admin/content/promo'
    | '/admin/content/testimonials'
    | '/admin/content/theme'
    | '/admin/customers/$id'
    | '/admin/orders/$id'
    | '/admin/products/$id'
    | '/admin/settings/countries'
    | '/admin/settings/couriers'
    | '/admin/settings/currency'
    | '/admin/settings/orders'
    | '/admin/settings/payments'
    | '/admin/settings/shipping'
    | '/admin/settings/store'
    | '/admin/settings/tax'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  EmailsRoute: typeof EmailsRoute
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OrdersRoute: typeof OrdersRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ShippingReturnsRoute: typeof ShippingReturnsRoute
  ShopRoute: typeof ShopRoute
  SizeGuideRoute: typeof SizeGuideRoute
  TermsRoute: typeof TermsRoute
  TrackOrderRoute: typeof TrackOrderRoute
  VerifyRoute: typeof VerifyRoute
  WishlistRoute: typeof WishlistRoute
  AdminLoginRoute: typeof AdminLoginRoute
  OrderIdRoute: typeof OrderIdRoute
  ProductSlugRoute: typeof ProductSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emails': {
      id: '/emails'
      path: '/emails'
      fullPath: '/emails'
      preLoaderRoute: typeof EmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping-returns': {
      id: '/shipping-returns'
      path: '/shipping-returns'
      fullPath: '/shipping-returns'
      preLoaderRoute: typeof ShippingReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/size-guide': {
      id: '/size-guide'
      path: '/size-guide'
      fullPath: '/size-guide'
      preLoaderRoute: typeof SizeGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track-order': {
      id: '/track-order'
      path: '/track-order'
      fullPath: '/track-order'
      preLoaderRoute: typeof TrackOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/abandoned': {
      id: '/admin/abandoned'
      path: '/abandoned'
      fullPath: '/admin/abandoned'
      preLoaderRoute: typeof AdminAbandonedRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/back-in-stock': {
      id: '/admin/back-in-stock'
      path: '/back-in-stock'
      fullPath: '/admin/back-in-stock'
      preLoaderRoute: typeof AdminBackInStockRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/discounts': {
      id: '/admin/discounts'
      path: '/discounts'
      fullPath: '/admin/discounts'
      preLoaderRoute: typeof AdminDiscountsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/drafts': {
      id: '/admin/drafts'
      path: '/drafts'
      fullPath: '/admin/drafts'
      preLoaderRoute: typeof AdminDraftsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscribers': {
      id: '/admin/subscribers'
      path: '/subscribers'
      fullPath: '/admin/subscribers'
      preLoaderRoute: typeof AdminSubscribersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/system': {
      id: '/admin/system'
      path: '/system'
      fullPath: '/admin/system'
      preLoaderRoute: typeof AdminSystemRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin_/login': {
      id: '/admin_/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$id': {
      id: '/order/$id'
      path: '/order/$id'
      fullPath: '/order/$id'
      preLoaderRoute: typeof OrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content/announcements': {
      id: '/admin/content/announcements'
      path: '/content/announcements'
      fullPath: '/admin/content/announcements'
      preLoaderRoute: typeof AdminContentAnnouncementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content/brand': {
      id: '/admin/content/brand'
      path: '/content/brand'
      fullPath: '/admin/content/brand'
      preLoaderRoute: typeof AdminContentBrandRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content/footer': {
      id: '/admin/content/footer'
      path: '/content/footer'
      fullPath: '/admin/content/footer'
      preLoaderRoute: typeof AdminContentFooterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content/header': {
      id: '/admin/content/header'
      path: '/content/header'
      fullPath: '/admin/content/header'
      preLoaderRoute: typeof AdminContentHeaderRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content/hero': {
      id: '/admin/content/hero'
      path: '/content/hero'
      fullPath: '/admin/content/hero'
      preLoaderRoute: typeof AdminContentHeroRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content/home': {
      id: '/admin/content/home'
      path: '/content/home'
      fullPath: '/admin/content/home'
      preLoaderRoute: typeof AdminContentHomeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content/newsletter': {
      id: '/admin/content/newsletter'
      path: '/content/newsletter'
      fullPath: '/admin/content/newsletter'
      preLoaderRoute: typeof AdminContentNewsletterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content/pages': {
      id: '/admin/content/pages'
      path: '/content/pages'
      fullPath: '/admin/content/pages'
      preLoaderRoute: typeof AdminContentPagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content/promo': {
      id: '/admin/content/promo'
      path: '/content/promo'
      fullPath: '/admin/content/promo'
      preLoaderRoute: typeof AdminContentPromoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content/testimonials': {
      id: '/admin/content/testimonials'
      path: '/content/testimonials'
      fullPath: '/admin/content/testimonials'
      preLoaderRoute: typeof AdminContentTestimonialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content/theme': {
      id: '/admin/content/theme'
      path: '/content/theme'
      fullPath: '/admin/content/theme'
      preLoaderRoute: typeof AdminContentThemeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers/$id': {
      id: '/admin/customers/$id'
      path: '/$id'
      fullPath: '/admin/customers/$id'
      preLoaderRoute: typeof AdminCustomersIdRouteImport
      parentRoute: typeof AdminCustomersRoute
    }
    '/admin/orders/$id': {
      id: '/admin/orders/$id'
      path: '/$id'
      fullPath: '/admin/orders/$id'
      preLoaderRoute: typeof AdminOrdersIdRouteImport
      parentRoute: typeof AdminOrdersRoute
    }
    '/admin/products/$id': {
      id: '/admin/products/$id'
      path: '/$id'
      fullPath: '/admin/products/$id'
      preLoaderRoute: typeof AdminProductsIdRouteImport
      parentRoute: typeof AdminProductsRoute
    }
    '/admin/settings/countries': {
      id: '/admin/settings/countries'
      path: '/settings/countries'
      fullPath: '/admin/settings/countries'
      preLoaderRoute: typeof AdminSettingsCountriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings/couriers': {
      id: '/admin/settings/couriers'
      path: '/settings/couriers'
      fullPath: '/admin/settings/couriers'
      preLoaderRoute: typeof AdminSettingsCouriersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings/currency': {
      id: '/admin/settings/currency'
      path: '/settings/currency'
      fullPath: '/admin/settings/currency'
      preLoaderRoute: typeof AdminSettingsCurrencyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings/orders': {
      id: '/admin/settings/orders'
      path: '/settings/orders'
      fullPath: '/admin/settings/orders'
      preLoaderRoute: typeof AdminSettingsOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings/payments': {
      id: '/admin/settings/payments'
      path: '/settings/payments'
      fullPath: '/admin/settings/payments'
      preLoaderRoute: typeof AdminSettingsPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings/shipping': {
      id: '/admin/settings/shipping'
      path: '/settings/shipping'
      fullPath: '/admin/settings/shipping'
      preLoaderRoute: typeof AdminSettingsShippingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings/store': {
      id: '/admin/settings/store'
      path: '/settings/store'
      fullPath: '/admin/settings/store'
      preLoaderRoute: typeof AdminSettingsStoreRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings/tax': {
      id: '/admin/settings/tax'
      path: '/settings/tax'
      fullPath: '/admin/settings/tax'
      preLoaderRoute: typeof AdminSettingsTaxRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminCustomersRouteChildren {
  AdminCustomersIdRoute: typeof AdminCustomersIdRoute
}

const AdminCustomersRouteChildren: AdminCustomersRouteChildren = {
  AdminCustomersIdRoute: AdminCustomersIdRoute,
}

const AdminCustomersRouteWithChildren = AdminCustomersRoute._addFileChildren(
  AdminCustomersRouteChildren,
)

interface AdminOrdersRouteChildren {
  AdminOrdersIdRoute: typeof AdminOrdersIdRoute
}

const AdminOrdersRouteChildren: AdminOrdersRouteChildren = {
  AdminOrdersIdRoute: AdminOrdersIdRoute,
}

const AdminOrdersRouteWithChildren = AdminOrdersRoute._addFileChildren(
  AdminOrdersRouteChildren,
)

interface AdminProductsRouteChildren {
  AdminProductsIdRoute: typeof AdminProductsIdRoute
}

const AdminProductsRouteChildren: AdminProductsRouteChildren = {
  AdminProductsIdRoute: AdminProductsIdRoute,
}

const AdminProductsRouteWithChildren = AdminProductsRoute._addFileChildren(
  AdminProductsRouteChildren,
)

interface AdminRouteChildren {
  AdminAbandonedRoute: typeof AdminAbandonedRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminBackInStockRoute: typeof AdminBackInStockRoute
  AdminCustomersRoute: typeof AdminCustomersRouteWithChildren
  AdminDiscountsRoute: typeof AdminDiscountsRoute
  AdminDraftsRoute: typeof AdminDraftsRoute
  AdminOrdersRoute: typeof AdminOrdersRouteWithChildren
  AdminProductsRoute: typeof AdminProductsRouteWithChildren
  AdminStaffRoute: typeof AdminStaffRoute
  AdminSubscribersRoute: typeof AdminSubscribersRoute
  AdminSystemRoute: typeof AdminSystemRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminContentAnnouncementsRoute: typeof AdminContentAnnouncementsRoute
  AdminContentBrandRoute: typeof AdminContentBrandRoute
  AdminContentFooterRoute: typeof AdminContentFooterRoute
  AdminContentHeaderRoute: typeof AdminContentHeaderRoute
  AdminContentHeroRoute: typeof AdminContentHeroRoute
  AdminContentHomeRoute: typeof AdminContentHomeRoute
  AdminContentNewsletterRoute: typeof AdminContentNewsletterRoute
  AdminContentPagesRoute: typeof AdminContentPagesRoute
  AdminContentPromoRoute: typeof AdminContentPromoRoute
  AdminContentTestimonialsRoute: typeof AdminContentTestimonialsRoute
  AdminContentThemeRoute: typeof AdminContentThemeRoute
  AdminSettingsCountriesRoute: typeof AdminSettingsCountriesRoute
  AdminSettingsCouriersRoute: typeof AdminSettingsCouriersRoute
  AdminSettingsCurrencyRoute: typeof AdminSettingsCurrencyRoute
  AdminSettingsOrdersRoute: typeof AdminSettingsOrdersRoute
  AdminSettingsPaymentsRoute: typeof AdminSettingsPaymentsRoute
  AdminSettingsShippingRoute: typeof AdminSettingsShippingRoute
  AdminSettingsStoreRoute: typeof AdminSettingsStoreRoute
  AdminSettingsTaxRoute: typeof AdminSettingsTaxRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAbandonedRoute: AdminAbandonedRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminBackInStockRoute: AdminBackInStockRoute,
  AdminCustomersRoute: AdminCustomersRouteWithChildren,
  AdminDiscountsRoute: AdminDiscountsRoute,
  AdminDraftsRoute: AdminDraftsRoute,
  AdminOrdersRoute: AdminOrdersRouteWithChildren,
  AdminProductsRoute: AdminProductsRouteWithChildren,
  AdminStaffRoute: AdminStaffRoute,
  AdminSubscribersRoute: AdminSubscribersRoute,
  AdminSystemRoute: AdminSystemRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminContentAnnouncementsRoute: AdminContentAnnouncementsRoute,
  AdminContentBrandRoute: AdminContentBrandRoute,
  AdminContentFooterRoute: AdminContentFooterRoute,
  AdminContentHeaderRoute: AdminContentHeaderRoute,
  AdminContentHeroRoute: AdminContentHeroRoute,
  AdminContentHomeRoute: AdminContentHomeRoute,
  AdminContentNewsletterRoute: AdminContentNewsletterRoute,
  AdminContentPagesRoute: AdminContentPagesRoute,
  AdminContentPromoRoute: AdminContentPromoRoute,
  AdminContentTestimonialsRoute: AdminContentTestimonialsRoute,
  AdminContentThemeRoute: AdminContentThemeRoute,
  AdminSettingsCountriesRoute: AdminSettingsCountriesRoute,
  AdminSettingsCouriersRoute: AdminSettingsCouriersRoute,
  AdminSettingsCurrencyRoute: AdminSettingsCurrencyRoute,
  AdminSettingsOrdersRoute: AdminSettingsOrdersRoute,
  AdminSettingsPaymentsRoute: AdminSettingsPaymentsRoute,
  AdminSettingsShippingRoute: AdminSettingsShippingRoute,
  AdminSettingsStoreRoute: AdminSettingsStoreRoute,
  AdminSettingsTaxRoute: AdminSettingsTaxRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  EmailsRoute: EmailsRoute,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OrdersRoute: OrdersRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ShippingReturnsRoute: ShippingReturnsRoute,
  ShopRoute: ShopRoute,
  SizeGuideRoute: SizeGuideRoute,
  TermsRoute: TermsRoute,
  TrackOrderRoute: TrackOrderRoute,
  VerifyRoute: VerifyRoute,
  WishlistRoute: WishlistRoute,
  AdminLoginRoute: AdminLoginRoute,
  OrderIdRoute: OrderIdRoute,
  ProductSlugRoute: ProductSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
